
version: 2

models:
  - name: int_hotspot
    description: Hotspots included in study that are within bounds of max and min city elevation
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - locality_id
            - city_id
    columns:
      - name: hotspot_id
        description: the unique identifier for this hotspot (locality_id, city_id)
        tests:
          - not_null
          - unique
      - name: locality_id
        description: The ID of the given hotspot
      - name: name
        description: The name of the hotspot
      - name: latitude
        description: the latitude of the hotspot
      - name: longitude
        description: the longitude of the hotspot
      - name: elevation
        description: the elevation of the hotspot
      - name: city_id
        description: the city this hotspot is related to
      - name: type
        description: whether this is hotspot is in the urban area or the surrounding buffer
        tests:
          - not_null
          - accepted_values:
              values: ['urban', 'buffer']

  - name: int_checklist
    description: Checklists at hotspots included in study
    columns:
      - name: checklist_id
        description: The ID of the given checklist
        tests:
          - unique
          - not_null
      - name: locality_id
        description: The hotspot this checklist was recorded at
        tests:
          - relationships:
              to: ref('int_hotspot')
              field: locality_id
      - name: observation_date
        description: The date the checklist was created
      - name: effort_distance_km
        description: The number of kilometers covered
      - name: effort_area_ha
        description: The area covered in hectares
      - name: duration_minutes
        description: The total time taken to produce the checklist

  - name: int_observation
    description: Individual observations at hotspots included in study
    columns:
      - name: observation_id
        description: The ID of this observation
      - name: scientific_name
        description: The scientific name for the bird seen
      - name: common_name
        description: The common name for the bird seen
      - name: observation_count
        description: The number of individuals seen
      - name: is_observation_count_provided
        description: whether a count was provided for all individuals seen
      - name: checklist_id
        description: The checklist this observation was submitted under
        tests:
          - relationships:
              to: ref('int_checklist')
              field: checklist_id

  - name: int_species_at_hotspot
    description: All species recorded on checklists at a hotspot
    columns:
      - name: hotspot_id
        description: the unique identifier for this hotspot (locality_id, city_id)
        tests:
          - relationships:
              to: ref('int_hotspot')
              field: hotspot_id
      - name: locality_id
        description: the hotspot
        tests:
          - relationships:
              to: ref('int_hotspot')
              field: locality_id
      - name: city_id
        description: the city the hotspot is in
        tests:
          - relationships:
              to: ref('city')
              field: city_id
      - name: scientific_name
        description: The scientific name for the bird seen
      - name: common_name
        description: The common name for the bird seen
      - name: number_of_checklists
        description: The number of checklists this species appears on
      - name: total_checklists_at_hotspot
        description: the total number of checklists at the hotspot
      - name: percentage_of_checklists
        description: the percentage of checklists the species appears on

  - name: eph_included_hotspot
    description: Hotspots included in study that have required number of checklists
    columns:
      - name: hotspot_id
        description: The unique key for the int_hotspot
      - name: locality_id
        description: The ID of the given hotspot
      - name: name
        description: The name of the hotspot
      - name: latitude
        description: the latitude of the hotspot
      - name: longitude
        description: the longitude of the hotspot
      - name: elevation
        description: the elevation of the hotspot
      - name: city_id
        description: the city this hotspot is related to
      - name: type
        description: whether this is hotspot is in the urban area or the surrounding buffer
      - name: number_of_checklists
        description: the number of checklists at the hotspot

  - name: int_birdlife_regional_species_pool
    description: Regional pool based on birdlife distribution polygons
    columns:
      - name: scientific_name
        description: The scientific name for the bird
      - name: common_name
        description: The common name for the bird
      - name: city_id
        description: the city this bird appears in the regional pool for,
      - name: iucn_red_list_2020
        description: IUCN red list category
      - name: presence
        description: The presence type for this region (e.g. extinct)
      - name: presence_code
        description: birdlist code for presence
      - name: origin
        description: The origin type for this region (e.g. native, introduced)
      - name: origin_code
        description: birdlist code for origin
      - name: seasonal
        description: The presence type for this region (e.g. breeding, passage, resident)
      - name: seasonal_code
        description: birdlist code for seasonal

  - name: int_ebird_regional_species_pool
    description: Regional pool based on ebird hotspots in buffer around urban area
    columns:
      - name: scientific_name
        description: The scientific name for the bird
      - name: common_name
        description: The common name for the bird
      - name: city_id
        description: the city this bird appears in the regional pool for
      - name: average_percentage_of_checklists
        description: The average number of checklists this species appears on across regional hotspots it appears at.
      - name: number_of_hotspot_appearances
        description: The number of hotspots this species appears at.