
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'urban_ebird'
version: '1.0.0'
config-version: 2

vars:
  # The max distance in elevation a regional hotspot can be either above or below the min/max elevation of urban hotspots.
  max_difference_in_elevation_for_regional_hotspot: 500
  # The minimum number of checklists that must be at a hotspot for its inclusion
  min_number_of_checklists_required_at_hotspot: 15
  # The minimum percentage of checklists that a species must appear in at a hotspot for it to be included
  min_percentage_of_checklists_for_species_at_hotspot: 10
  # Defining min/max effort allowed for checklists
  max_distance_travelled_for_checklist_km: 10
  min_duration_for_checklist: 5
  max_duration_for_checklist: 240
  # Only include checklists equal or after this year
  min_year_for_inclusion: 2014
  
# This setting configures which "profile" dbt uses for this project.
profile: 'urban_ebird'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  urban_ebird:
    ebird:
      materialized: view
      +schema: ebird
    intermediate:
      materialized: table
      +schema: intermediate
    model:
      materialized: view
      +schema: model