
version: 2

models:
  - name: hotspot
    description: Individual hotspots found in eBird dataset
    columns:
      - name: locality_id
        description: The ID of the given hotspot
        tests:
          - unique
          - not_null
      - name: name
        description: The name of the hotspot
        tests:
          - not_null
      - name: latitude
        description: the latitude of the hotspot
        tests:
          - not_null
      - name: longitude
        description: the longitude of the hotspot
        tests:
          - not_null

  - name: checklist
    description: Individual checklists found in eBird dataset at hotspots
    columns:
      - name: checklist_id
        description: The ID of the given checklist
        tests:
          - unique
          - not_null
      - name: locality_id
        description: The hotspot this checklist was recorded at
        tests:
          -  not_null
          - relationships:
              to: ref('hotspot')
              field: locality_id
      - name: number_observers
        description: The number of observers finding birds on the checklist
      - name: observation_date
        description: The date the checklist was created
        tests:
          - not_null
      - name: effort_distance_km
        description: The number of kilometers covered
      - name: effort_area_ha
        description: The area covered in hectares
      - name: duration_minutes
        description: The total time taken to produce the checklist
      - name: protocol_type
        description: The protocol observed when creating the checklist

  - name: observation
    description: Individual approved observations found on eBird checklist
    columns:
      - name: observation_id
        description: The ID of this observation
        tests:
          - unique
          - not_null
      - name: scientific_name
        description: The scientific name for the bird seen
        tests:
          - not_null
      - name: subspecies_scientific_name
        description: The scientific subspecies name, may be null.
      - name: common_name
        description: The common name for the bird seen
        tests:
          - not_null
      - name: subspecies_common_name
        description: The common subspecies name, may be null
      - name: observation_count
        description: The number of individuals seen, may be 'X' to indicate present
      - name: checklist_id
        description: The checklist this observation was submitted under
        tests:
          - not_null
          - relationships:
              to: ref('checklist')
              field: checklist_id

  - name: city
    description: Potential cities to be included in study that have population over 2 million and eBird hotspots
    columns:
      - name: city_id
        description: The ID of this city
        tests:
          - unique
          - not_null
      - name: name
        description: The name of this city
        tests:
          - not_null
          - unique
      - name: population_2015
        description: The city population in 2015
        tests:
          - not_null
      - name: built_area_2015
        description: The built up area of the city in 2015
        tests:
          - not_null
      - name: latitude
        description: the latitude of the city from nordpil or wikipedia
        tests:
          - not_null
      - name: longitude
        description: the longitude of the city from nordpil or wikipedia
        tests:
          - not_null
      - name: min_urban_hotspot_elevation
        description: The minimum elevation of any hotspot inside the city
        tests:
          - not_null
      - name: max_urban_hotspot_elevation
        description: The maximum elevation of any hotspot inside the city
        tests:
          - not_null
      - name: min_regional_hotspot_elevation
        description: The minimum elevation of any hotspot outside the city
        tests:
          - not_null
      - name: max_regional_hotspot_elevation
        description: The maximum elevation of any hotspot outside the city
        tests:
          - not_null
  - name: hotspot_to_city
    description: Join table from potential cities to hotspots
    columns:
      - name: city_id
        description: The city this hotspot is associated with
        tests:
          - not_null
          - relationships:
              to: ref('city')
              field: city_id
      - name: locality_id
        description: The hotspot associated with the city
        tests:
          - not_null
          - relationships:
              to: ref('hotspot')
              field: locality_id
      - name: type
        description: whether this is an urban hotspot or in the buffer
        tests:
          - not_null
          - accepted_values:
              values: ['urban', 'buffer']
      - name: elevation
        description: The elevation of this hotspot
        tests:
          - not_null
