
version: 2

models:
  - name: eph_included_hotspot
    description: Hotspots included in study that have required number of checklists
    columns:
      - name: locality_id
        description: The ID of the given hotspot
      - name: name
        description: The name of the hotspot
      - name: latitude
        description: the latitude of the hotspot
      - name: longitude
        description: the longitude of the hotspot
      - name: elevation
        description: the elevation of the hotspot
      - name: city_id
        description: the city this hotspot is related to
      - name: type
        description: whether this is hotspot is in the urban area or the surrounding buffer
      - name: number_of_checklists
        description: the number of checklists at the hotspot

  - name: eph_included_species_at_hotspot
    description: Species that appear on over the required percentage of checklists at a hotspot
    columns:
      - name: locality_id
        description: the hotspot
      - name: city_id
        description: the city the hotspot is in
      - name: scientific_name
        description: The scientific name for the bird seen
      - name: common_name
        description: The common name for the bird seen
      - name: number_of_checklists
        description: The number of checklists this species appears on
      - name: total_checklists_at_hotspot
        description: the total number of checklists at the hotspot
      - name: percentage_of_checklists
        description: the percentage of checklists the species appears on

  - name: regional_species
    description: Species in the regional species pool for a city
    columns:
      - name: city_id
        description: the city the hotspot is in
      - name: scientific_name
        description: The scientific name for the bird seen
      - name: common_name
        description: The common name for the bird seen
      - name: average_percentage_of_checklists
        description: The average percentage of checklists this species appears on at hotspots within the region
      - name: number_of_hotspot_appearances
        description: The number of hotspots this species appears on

  - name: urban_area
    description: Details of the urban areas with in the study
    columns:
      - name: city_id
        description: The ID of this city
      - name: name
        description: The name of this city
      - name: population_2015
        description: The city population in 2015
      - name: built_area_2015
        description: The built up area of the city in 2015
      - name: latitude
        description: the latitude of the city from nordpil or wikipedia
      - name: longitude
        description: the longitude of the city from nordpil or wikipedia
      - name: total_urban_hotspots
        description: the total number of hotspots within this city included in study
      - name: total_regional_hotspots
        description: the total number of hotspots within the region around this city included in study
      - name: urban_richness
        description: the urban species richness
      - name: regional_richness
        description: the regional species pool richness
      - name: min_urban_hotspot_elevation
        description: The minimum elevation of any hotspot inside the city
      - name: max_urban_hotspot_elevation
        description: The maximum elevation of any hotspot inside the city
      - name: min_regional_hotspot_elevation
        description: The minimum elevation of any hotspot outside the city, taking into account max difference allowed
      - name: max_regional_hotspot_elevation
        description: The maximum elevation of any hotspot outside the city, taking into account max difference allowed

  - name: urban_hotspot
    description: Hotspot included in study within an urban areay
    columns:
      - name: locality_id
        description: The ID of the given hotspot
      - name: name
        description: The name of the hotspot
      - name: latitude
        description: the latitude of the hotspot
      - name: longitude
        description: the longitude of the hotspot
      - name: elevation
        description: the elevation of the hotspot
      - name: city_id
        description: the city this hotspot is related to
      - name: number_of_checklists
        description: the number of checklists at the hotspot
      - name: richmess
        description: the species richness at this hotspot

  - name: urban_species
    description: Species that occur at urban hotspots
    columns:
      - name: city_id
        description: the city the hotspot is in
      - name: locality_id
        description: the hotspot
      - name: scientific_name
        description: The scientific name for the bird seen
      - name: common_name
        description: The common name for the bird seen
      - name: percentage_of_checklists
        description: The percentage of checklists this species appears on at hotspots within the regional