
version: 2

models:
  - name: regional_species
    description: Species in the regional species pool for a city
    columns:
      - name: city_id
        description: the city the hotspot is in
        tests:
          - not_null
          - relationships:
              to: ref('urban_area')
              field: city_id
      - name: scientific_name
        description: The scientific name for the bird seen
        tests:
          - not_null
      - name: common_name
        description: The common name for the bird seen
        tests:
          - not_null
      - name: average_percentage_of_checklists
        description: The average percentage of checklists this species appears on at hotspots within the regionl
        tests:
          - not_null

  - name: urban_area
    description: Details of the urban areas with in the study
    columns:
      - name: city_id
        description: The ID of this city
        tests:
          - unique
          - not_null
      - name: name
        description: The name of this city
        tests:
          - not_null
          - unique
      - name: population_2015
        description: The city population in 2015
      - name: built_area_2015
        description: The built up area of the city in 2015
      - name: latitude
        description: the latitude of the city from nordpil or wikipedia
      - name: longitude
        description: the longitude of the city from nordpil or wikipedia
      - name: total_urban_hotspots
        description: the total number of hotspots within this city included in study
      - name: total_regional_hotspots
        description: the total number of hotspots within the region around this city included in study
      - name: urban_richness
        description: the urban species richness
      - name: regional_richness
        description: the regional species pool richness
      - name: min_urban_hotspot_elevation
        description: The minimum elevation of any hotspot inside the city
        tests:
          - not_null
      - name: max_urban_hotspot_elevation
        description: The maximum elevation of any hotspot inside the city
        tests:
          - not_null
      - name: min_regional_hotspot_elevation
        description: The minimum elevation of any hotspot outside the city, taking into account max difference allowed
        tests:
          - not_null
      - name: max_regional_hotspot_elevation
        description: The maximum elevation of any hotspot outside the city, taking into account max difference allowed
        tests:
          - not_null

  - name: urban_hotspot
    description: Hotspot included in study within an urban areay
    columns:
      - name: locality_id
        description: The ID of the given hotspot
        tests:
          - unique
          - not_null
      - name: name
        description: The name of the hotspot
        tests:
          - not_null
      - name: latitude
        description: the latitude of the hotspot
        tests:
          - not_null
      - name: longitude
        description: the longitude of the hotspot
        tests:
          - not_null
      - name: elevation
        description: the elevant of the hotspot in m
        tests:
          - not_null
      - name: city_id
        description: the city this hotspot is related to
        tests:
          - not_null
      - name: number_of_checklists
        description: the number of checklists at the hotspot
        tests:
          - not_null
      - name: richmess
        description: the species richness at this hotspot
        tests:
          - not_null

  - name: urban_species
    description: Species that occur at urban hotspots
    columns:
      - name: city_id
        description: the city the hotspot is in
        tests:
          - not_null
          - relationships:
              to: ref('urban_area')
              field: city_id

      - name: locality_id
        description: the hotspot
        tests:
          - not_null
          - relationships:
              to: ref('urban_hotspot')
              field: locality_id
      - name: scientific_name
        description: The scientific name for the bird seen
        tests:
          - not_null
      - name: common_name
        description: The common name for the bird seen
        tests:
          - not_null
      - name: percentage_of_checklists
        description: The percentage of checklists this species appears on at hotspots within the regionl
        tests:
          - not_null