
version: 2

models:
  - name: regional_species
    description: Species in the regional species pool for a city
    columns:
      - name: city_id
        description: the city the hotspot is in
      - name: scientific_name
        description: The scientific name for the bird seen
        tests:
          - relationships:
              to: ref('taxonomy')
              field: scientific_name
      - name: common_name
        description: The common name for the bird seen
      - name: present_in_birdlife
        description: Whether this species is present in the birdlife compiled species pool
      - name: present_in_ebird
        description: Whether this species is present in the ebird compiled species pool
      - name: present_in_either_pool
        description: Whether this species is present in the birdlife or the merlin compiled species pool
      - name: present_in_both_pools
        description: Whether this species is present in the ebird and the merlin compiled species pool
      - name: present_in_city
        description: Whether this species is present in an ebird urban hotspot

  - name: urban_area
    description: Details of the urban areas with in the study using birdlife regional pool
    columns:
      - name: city_id
        description: The ID of this city
      - name: name
        description: The name of this city
      - name: population_2015
        description: The city population in 2015
      - name: built_area_2015
        description: The built up area of the city in 2015
      - name: latitude
        description: the latitude of the city from nordpil or wikipedia
      - name: longitude
        description: the longitude of the city from nordpil or wikipedia
      - name: total_urban_hotspots
        description: the total number of hotspots within this city included in study

  - name: urban_hotspot
    description: Hotspot included in study within an urban areay
    columns:
      - name: hotspot_id
        description: The ID of the hotspot
        tests:
          - unique
      - name: locality_id
        description: The ID of the given ebird locality
        tests:
          - unique
      - name: name
        description: The name of the hotspot
      - name: latitude
        description: the latitude of the hotspot
      - name: longitude
        description: the longitude of the hotspot
      - name: elevation
        description: the elevation of the hotspot
      - name: city_id
        description: the city this hotspot is related to
      - name: number_of_checklists
        description: the number of checklists at the hotspot

  - name: taxonomy
    description: The taxonomic model based on eBird/Clements used
    columns:
      - name: scientific_name
        description: species bionomial
      - name: common_name
        description: the English common name
      - name: taxonomic_order
        description: The species order
      - name: taxonomic_family
        description: The species family
      - name: iucn_red_list_2020
        description: The IUCN vulnerability from 2020
        tests:
          - not_null
      - name: diet
        description: description of species diet
      - name: foraging
        description: how the species forages